__CONTEXT__

League of Legends is a MOBA (multiplayer online battle arena) where 2 teams (blue and red) face off. There are 3 lanes, a jungle, and 5 roles. The goal is to take down the enemy Nexus to win the game.

__GLOSSARY__

- Warding totem: An item that a player can put on the map to reveal the nearby area. Very useful for map/objectives control.

- Minions: NPC that belong to both teams. They give gold when killed by players.

- Jungle minions: NPC that belong to NO TEAM. They give gold and buffs when killed by players.

- Elite monsters: Monsters with high hp/damage that give a massive bonus (gold/XP/stats) when killed by a team.

- Dragons: Elite monster which gives team bonus when killed. The 4th dragon killed by a team - gives a massive stats bonus. The - - 5th dragon (Elder Dragon) offers a huge advantage to the team.

- Herald: Elite monster which gives stats bonus when killed by the player. It helps to push a lane and destroys structures.

- Towers: Structures you have to destroy to reach the enemy Nexus. They give gold.

- Level: Champion level. Start at 1. Max is 18.

__CONTENT__

This dataset contains the first 10min. stats of approx. 10k ranked games (SOLO QUEUE) from a high ELO (DIAMOND I to MASTER). Players have roughly the same level (ELO).

Each game is unique. The gameId can help you to fetch more attributes from the Riot API.

There are 19 features per team (38 in total) collected after 10min in-game. This includes kills, deaths, gold, experience, levelâ€¦

In [5]:
import pandas as pd
import numpy as np

In [6]:
# the supplied CSV data file is in the data directory
LoL_data = pd.read_csv('C:\\Users\\luisr\\OneDrive\\Documents\\SpringBoard\\LoLPredictor\\LoLPredictor\\data\\raw\\high_diamond_ranked_10min.csv')

In [7]:
# Summary of the data
LoL_data.info()
LoL_data.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9879 entries, 0 to 9878
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   gameId                        9879 non-null   int64
 1   blueWins                      9879 non-null   int64
 2   blueWardsPlaced               9879 non-null   int64
 3   blueWardsDestroyed            9879 non-null   int64
 4   blueFirstBlood                9879 non-null   int64
 5   blueKills                     9879 non-null   int64
 6   blueDeaths                    9879 non-null   int64
 7   blueAssists                   9879 non-null   int64
 8   blueEliteMonsters             9879 non-null   int64
 9   blueDragons                   9879 non-null   int64
 10  blueHeralds                   9879 non-null   int64
 11  blueTowersDestroyed           9879 non-null   int64
 12  blueTotalGold                 9879 non-null   int64
 13  blueAvgLevel                  9879 non-null   float64
 14  blueTotalExperience           9879 non-null   int64
 15  blueTotalMinionsKilled        9879 non-null   int64
 16  blueTotalJungleMinionsKilled  9879 non-null   int64
 17  blueGoldDiff                  9879 non-null   int64
 18  blueExperienceDiff            9879 non-null   int64
 19  blueCSPerMin                  9879 non-null   float64
 20  blueGoldPerMin                9879 non-null   float64
 21  redWardsPlaced                9879 non-null   int64
 22  redWardsDestroyed             9879 non-null   int64
 23  redFirstBlood                 9879 non-null   int64
 24  redKills                      9879 non-null   int64
 25  redDeaths                     9879 non-null   int64
 26  redAssists                    9879 non-null   int64
 27  redEliteMonsters              9879 non-null   int64
 28  redDragons                    9879 non-null   int64
 29  redHeralds                    9879 non-null   int64
 30  redTowersDestroyed            9879 non-null   int64
 31  redTotalGold                  9879 non-null   int64
 32  redAvgLevel                   9879 non-null   float64
 33  redTotalExperience            9879 non-null   int64
 34  redTotalMinionsKilled         9879 non-null   int64
 35  redTotalJungleMinionsKilled   9879 non-null   int64
 36  redGoldDiff                   9879 non-null   int64
 37  redExperienceDiff             9879 non-null   int64
 38  redCSPerMin                   9879 non-null   float64
 39  redGoldPerMin                 9879 non-null   float64
dtypes: float64(6), int64(34)
memory usage: 3.0 MB

(9879, 40)

In [8]:
# Preview data
pd.options.display.max_columns = None
LoL_data.head(20)

,gameId,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeralds,blueTowersDestroyed,blueTotalGold,blueAvgLevel,blueTotalExperience,blueTotalMinionsKilled,blueTotalJungleMinionsKilled,blueGoldDiff,blueExperienceDiff,blueCSPerMin,blueGoldPerMin,redWardsPlaced,redWardsDestroyed,redFirstBlood,redKills,redDeaths,redAssists,redEliteMonsters,redDragons,redHeralds,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
0,4519157822,0,28,2,1,9,6,11,0,0,0,0,17210,6.6,17039,195,36,643,-8,19.5,1721.0,15,6,0,6,9,8,0,0,0,0,16567,6.8,17047,197,55,-643,8,19.7,1656.7
1,4523371949,0,12,1,0,5,5,5,0,0,0,0,14712,6.6,16265,174,43,-2908,-1173,17.4,1471.2,12,1,1,5,5,2,2,1,1,1,17620,6.8,17438,240,52,2908,1173,24.0,1762.0
2,4521474530,0,15,0,0,7,11,4,1,1,0,0,16113,6.4,16221,186,46,-1172,-1033,18.6,1611.3,15,3,1,11,7,14,0,0,0,0,17285,6.8,17254,203,28,1172,1033,20.3,1728.5
3,4524384067,0,43,1,0,4,5,5,1,0,1,0,15157,7.0,17954,201,55,-1321,-7,20.1,1515.7,15,2,1,5,4,10,0,0,0,0,16478,7.0,17961,235,47,1321,7,23.5,1647.8
4,4436033771,0,75,4,0,6,6,6,0,0,0,0,16400,7.0,18543,210,57,-1004,230,21.0,1640.0,17,2,1,6,6,7,1,1,0,0,17404,7.0,18313,225,67,1004,-230,22.5,1740.4
5,4475365709,1,18,0,0,5,3,6,1,1,0,0,15899,7.0,18161,225,42,698,101,22.5,1589.9,36,5,1,3,5,2,0,0,0,0,15201,7.0,18060,221,59,-698,-101,22.1,1520.1
6,4493010632,1,18,3,1,7,6,7,1,1,0,0,16874,6.8,16967,225,53,2411,1563,22.5,1687.4,57,1,0,6,7,9,0,0,0,0,14463,6.4,15404,164,35,-2411,-1563,16.4,1446.3
7,4496759358,0,16,2,0,5,13,3,0,0,0,0,15305,6.4,16138,209,48,-2615,-800,20.9,1530.5,15,0,1,13,5,11,1,1,0,0,17920,6.6,16938,157,54,2615,800,15.7,1792.0
8,4443048030,0,16,3,0,7,7,8,0,0,0,0,16401,7.2,18527,189,61,-1979,-771,18.9,1640.1,15,2,1,7,7,5,2,1,1,0,18380,7.2,19298,240,53,1979,771,24.0,1838.0
9,4509433346,1,13,1,1,4,5,5,1,1,0,0,15057,6.8,16805,220,39,-1548,-1574,22.0,1505.7,16,2,0,5,4,4,0,0,0,0,16605,6.8,18379,247,43,1548,1574,24.7,1660.5
10,4452162573,0,20,3,1,4,4,6,0,0,0,0,15474,6.6,16611,231,28,331,-1585,23.1,1547.4,15,2,0,4,4,5,1,1,0,0,15143,7.2,18196,216,51,-331,1585,21.6,1514.3
11,4453038156,0,33,2,1,11,11,7,1,0,1,0,16695,7.0,18507,157,40,-1505,-635,15.7,1669.5,17,1,0,11,11,9,0,0,0,0,18200,7.0,19142,188,52,1505,635,18.8,1820.0
12,4515594785,1,18,1,1,7,1,11,1,1,0,0,17865,7.4,19102,238,53,3274,1659,23.8,1786.5,12,1,0,1,7,1,0,0,0,0,14591,6.8,17443,240,50,-3274,-1659,24.0,1459.1
13,4524924257,0,14,3,0,4,9,1,1,0,1,0,14979,6.6,17213,210,52,-3414,-1141,21.0,1497.9,20,3,1,9,4,11,0,0,0,0,18393,7.2,18354,229,51,3414,1141,22.9,1839.3
14,4516505202,1,15,3,1,4,4,4,0,0,0,0,15722,6.8,17896,224,51,-470,-187,22.4,1572.2,102,1,0,4,4,3,0,0,0,0,16192,7.0,18083,242,48,470,187,24.2,1619.2
15,4482120064,0,17,1,0,3,7,3,0,0,0,0,15015,6.8,16974,209,53,-1996,-1804,20.9,1501.5,18,3,1,7,3,13,0,0,0,0,17011,7.2,18778,237,51,1996,1804,23.7,1701.1
16,4523758462,1,14,1,1,10,2,8,0,0,0,0,19733,7.6,20862,263,56,5228,3378,26.3,1973.3,13,2,0,2,10,2,1,1,0,0,14505,6.8,17484,210,64,-5228,-3378,21.0,1450.5
17,4503636905,0,43,3,0,3,7,3,1,0,1,0,14852,6.8,16888,203,54,-1975,-1345,20.3,1485.2,17,14,1,7,3,6,0,0,0,0,16827,6.8,18233,218,53,1975,1345,21.8,1682.7
18,4486384947,1,21,4,1,5,4,11,0,0,0,0,16282,6.8,17378,213,49,882,512,21.3,1628.2,19,3,0,4,5,3,2,1,1,0,15400,6.6,16866,228,52,-882,-512,22.8,1540.0
19,4457103291,0,11,3,0,5,9,5,0,0,0,0,14994,7.0,17924,188,48,-3155,-2773,18.8,1499.4,15,1,1,9,5,9,0,0,0,0,18149,7.4,20697,219,56,3155,2773,21.9,1814.9

In [9]:
# Copy raw data to analyze and clean
lol_clean = LoL_data.copy()

In [10]:
# Eliminate aggregate columns
# gameId is not a feature in the game, simply an identifier for each match
lol_clean = lol_clean.drop('gameId', axis=1)

# Delete elite moster kills it is an aggregate of two other columns ('blueEliteMonsters' + 'blueHeralds' = blueEliteMonsters)
lol_clean = lol_clean.drop('blueEliteMonsters', axis=1)

# Delete elite moster kills it is an aggregate of two other columns ('redEliteMonsters' + 'redHeralds' = redEliteMonsters)
lol_clean = lol_clean.drop('redEliteMonsters', axis=1)
lol_clean

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueDragons,blueHeralds,blueTowersDestroyed,blueTotalGold,blueAvgLevel,blueTotalExperience,blueTotalMinionsKilled,blueTotalJungleMinionsKilled,blueGoldDiff,blueExperienceDiff,blueCSPerMin,blueGoldPerMin,redWardsPlaced,redWardsDestroyed,redFirstBlood,redKills,redDeaths,redAssists,redDragons,redHeralds,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
0,0,28,2,1,9,6,11,0,0,0,17210,6.6,17039,195,36,643,-8,19.5,1721.0,15,6,0,6,9,8,0,0,0,16567,6.8,17047,197,55,-643,8,19.7,1656.7
1,0,12,1,0,5,5,5,0,0,0,14712,6.6,16265,174,43,-2908,-1173,17.4,1471.2,12,1,1,5,5,2,1,1,1,17620,6.8,17438,240,52,2908,1173,24.0,1762.0
2,0,15,0,0,7,11,4,1,0,0,16113,6.4,16221,186,46,-1172,-1033,18.6,1611.3,15,3,1,11,7,14,0,0,0,17285,6.8,17254,203,28,1172,1033,20.3,1728.5
3,0,43,1,0,4,5,5,0,1,0,15157,7.0,17954,201,55,-1321,-7,20.1,1515.7,15,2,1,5,4,10,0,0,0,16478,7.0,17961,235,47,1321,7,23.5,1647.8
4,0,75,4,0,6,6,6,0,0,0,16400,7.0,18543,210,57,-1004,230,21.0,1640.0,17,2,1,6,6,7,1,0,0,17404,7.0,18313,225,67,1004,-230,22.5,1740.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9874,1,17,2,1,7,4,5,1,0,0,17765,7.2,18967,211,69,2519,2469,21.1,1776.5,46,3,0,4,7,7,0,0,0,15246,6.8,16498,229,34,-2519,-2469,22.9,1524.6
9875,1,54,0,0,6,4,8,1,0,0,16238,7.2,19255,233,48,782,888,23.3,1623.8,12,21,1,4,6,3,0,0,0,15456,7.0,18367,206,56,-782,-888,20.6,1545.6
9876,0,23,1,0,6,7,5,0,0,0,15903,7.0,18032,210,45,-2416,-1877,21.0,1590.3,14,0,1,7,6,11,1,0,0,18319,7.4,19909,261,60,2416,1877,26.1,1831.9
9877,0,14,4,1,2,3,3,1,0,0,14459,6.6,17229,224,48,-839,-1085,22.4,1445.9,66,4,0,3,2,1,0,0,0,15298,7.2,18314,247,40,839,1085,24.7,1529.8
9878,1,18,0,1,6,6,5,0,0,0,16266,7.0,17321,207,44,927,-58,20.7,1626.6,9,2,0,6,6,4,1,0,0,15339,6.8,17379,201,46,-927,58,20.1,1533.9

In [11]:
# Let's check for missing values by column and mean
missing = pd.concat([lol_clean.isnull().sum(), 100 * lol_clean.mean()], axis=1)
missing.columns=['count', '%']
missing.sort_values(by='count', ascending=False)

                              count             %
blueWins                          0  4.990384e+01
redWardsPlaced                    0  2.236795e+03
redFirstBlood                     0  4.951918e+01
redKills                          0  6.137666e+02
redDeaths                         0  6.183925e+02
redAssists                        0  6.662112e+02
redDragons                        0  4.130985e+01
redHeralds                        0  1.600364e+01
redTowersDestroyed                0  4.302055e+00
redTotalGold                      0  1.648904e+06
redAvgLevel                       0  6.925316e+02
redTotalExperience                0  1.796173e+06
redTotalMinionsKilled             0  2.173492e+04
redTotalJungleMinionsKilled       0  5.131309e+03
redGoldDiff                       0 -1.441411e+03
redExperienceDiff                 0  3.362031e+03
redCSPerMin                       0  2.173492e+03
redWardsDestroyed                 0  2.723150e+02
blueGoldPerMin                    0  1.650346e+05
blueWardsPlaced                   0  2.228829e+03
blueCSPerMin                      0  2.166996e+03
blueWardsDestroyed                0  2.824881e+02
blueFirstBlood                    0  5.048082e+01
blueKills                         0  6.183925e+02
blueDeaths                        0  6.137666e+02
blueAssists                       0  6.645106e+02
blueDragons                       0  3.619800e+01
blueHeralds                       0  1.879745e+01
blueTowersDestroyed               0  5.142221e+00
blueTotalGold                     0  1.650346e+06
blueAvgLevel                      0  6.916004e+02
blueTotalExperience               0  1.792811e+06
blueTotalMinionsKilled            0  2.166996e+04
blueTotalJungleMinionsKilled      0  5.050967e+03
blueGoldDiff                      0  1.441411e+03
blueExperienceDiff                0 -3.362031e+03
redGoldPerMin                     0  1.648904e+05

Luckly our data shows we have no missing values which we can be confident since that data came from Riots API.

In [12]:
lol_clean.info()
lol_clean.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9879 entries, 0 to 9878
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   blueWins                      9879 non-null   int64
 1   blueWardsPlaced               9879 non-null   int64
 2   blueWardsDestroyed            9879 non-null   int64
 3   blueFirstBlood                9879 non-null   int64
 4   blueKills                     9879 non-null   int64
 5   blueDeaths                    9879 non-null   int64
 6   blueAssists                   9879 non-null   int64
 7   blueDragons                   9879 non-null   int64
 8   blueHeralds                   9879 non-null   int64
 9   blueTowersDestroyed           9879 non-null   int64
 10  blueTotalGold                 9879 non-null   int64
 11  blueAvgLevel                  9879 non-null   float64
 12  blueTotalExperience           9879 non-null   int64
 13  blueTotalMinionsKilled        9879 non-null   int64
 14  blueTotalJungleMinionsKilled  9879 non-null   int64
 15  blueGoldDiff                  9879 non-null   int64
 16  blueExperienceDiff            9879 non-null   int64
 17  blueCSPerMin                  9879 non-null   float64
 18  blueGoldPerMin                9879 non-null   float64
 19  redWardsPlaced                9879 non-null   int64
 20  redWardsDestroyed             9879 non-null   int64
 21  redFirstBlood                 9879 non-null   int64
 22  redKills                      9879 non-null   int64
 23  redDeaths                     9879 non-null   int64
 24  redAssists                    9879 non-null   int64
 25  redDragons                    9879 non-null   int64
 26  redHeralds                    9879 non-null   int64
 27  redTowersDestroyed            9879 non-null   int64
 28  redTotalGold                  9879 non-null   int64
 29  redAvgLevel                   9879 non-null   float64
 30  redTotalExperience            9879 non-null   int64
 31  redTotalMinionsKilled         9879 non-null   int64
 32  redTotalJungleMinionsKilled   9879 non-null   int64
 33  redGoldDiff                   9879 non-null   int64
 34  redExperienceDiff             9879 non-null   int64
 35  redCSPerMin                   9879 non-null   float64
 36  redGoldPerMin                 9879 non-null   float64
dtypes: float64(6), int64(31)
memory usage: 2.8 MB

(9879, 37)

In [14]:
# save the data to a new csv file
lol_clean.to_csv('..\\data\\processed\\lol_clean_data', index=False)

__SUMMARY__

This project aims to build a predictive model for 'blueWins' & 'redWins' since these columns are mutually exclusive we will create a model for each side. 

Columns excluded:

- 'gameId'this column is not a feature in the game but simply an identifier

- 'blueEliteMonsters' is an aggregate of two other columns ('blueEliteMonsters' + 'blueHeralds' = blueEliteMonsters)

- 'redEliteMonsters' is an aggregate of two other columns ('redEliteMonsters' + 'rederalds' = redEliteMonsters)

Our original dataset contained 9,879 games with each game containing an in game feature. After our initial observation we deleted 3 columns and 0 rows. Our dataset shows some signs of multicollinearity but futher analysis is require to alter data.