In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [3]:
df = pd.read_csv('..\\data\\interim\\lol_clean_data.csv')
df.describe()

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueDragons,blueHeralds,blueTowersDestroyed,...,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
count,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,...,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000,9879.000000
mean,0.499038,22.288288,2.824881,0.504808,6.183925,6.137666,6.645106,0.361980,0.187974,0.051422,...,0.043021,16489.041401,6.925316,17961.730438,217.349226,51.313088,-14.414111,33.620306,21.734923,1648.904140
std,0.500024,18.019177,2.174998,0.500002,3.011028,2.933818,4.064520,0.480597,0.390712,0.244369,...,0.216900,1490.888406,0.305311,1198.583912,21.911668,10.027885,2453.349179,1920.370438,2.191167,149.088841
min,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,11212.000000,4.800000,10465.000000,107.000000,4.000000,-11467.000000,-8348.000000,10.700000,1121.200000
25%,0.000000,14.000000,1.000000,0.000000,4.000000,4.000000,4.000000,0.000000,0.000000,0.000000,...,0.000000,15427.500000,6.800000,17209.500000,203.000000,44.000000,-1596.000000,-1212.000000,20.300000,1542.750000
50%,0.000000,16.000000,3.000000,1.000000,6.000000,6.000000,6.000000,0.000000,0.000000,0.000000,...,0.000000,16378.000000,7.000000,17974.000000,218.000000,51.000000,-14.000000,28.000000,21.800000,1637.800000
75%,1.000000,20.000000,4.000000,1.000000,8.000000,8.000000,9.000000,1.000000,0.000000,0.000000,...,0.000000,17418.500000,7.200000,18764.500000,233.000000,57.000000,1585.500000,1290.500000,23.300000,1741.850000
max,1.000000,250.000000,27.000000,1.000000,22.000000,22.000000,29.000000,1.000000,1.000000,4.000000,...,2.000000,22732.000000,8.200000,22269.000000,289.000000,92.000000,10830.000000,9333.000000,28.900000,2273.200000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9879 entries, 0 to 9878
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   blueWins                      9879 non-null   int64
 1   blueWardsPlaced               9879 non-null   int64
 2   blueWardsDestroyed            9879 non-null   int64
 3   blueFirstBlood                9879 non-null   int64
 4   blueKills                     9879 non-null   int64
 5   blueDeaths                    9879 non-null   int64
 6   blueAssists                   9879 non-null   int64
 7   blueDragons                   9879 non-null   int64
 8   blueHeralds                   9879 non-null   int64
 9   blueTowersDestroyed           9879 non-null   int64
 10  blueTotalGold                 9879 non-null   int64
 11  blueAvgLevel                  9879 non-null   float64
 12  blueTotalExperience           9879 non-null   int64
 13  blueTotalMinionsKilled        9879 non-null   int64
 14  blueTotalJungleMinionsKilled  9879 non-null   int64
 15  blueGoldDiff                  9879 non-null   int64
 16  blueExperienceDiff            9879 non-null   int64
 17  blueCSPerMin                  9879 non-null   float64
 18  blueGoldPerMin                9879 non-null   float64
 19  redWardsPlaced                9879 non-null   int64
 20  redWardsDestroyed             9879 non-null   int64
 21  redFirstBlood                 9879 non-null   int64
 22  redKills                      9879 non-null   int64
 23  redDeaths                     9879 non-null   int64
 24  redAssists                    9879 non-null   int64
 25  redDragons                    9879 non-null   int64
 26  redHeralds                    9879 non-null   int64
 27  redTowersDestroyed            9879 non-null   int64
 28  redTotalGold                  9879 non-null   int64
 29  redAvgLevel                   9879 non-null   float64
 30  redTotalExperience            9879 non-null   int64
 31  redTotalMinionsKilled         9879 non-null   int64
 32  redTotalJungleMinionsKilled   9879 non-null   int64
 33  redGoldDiff                   9879 non-null   int64
 34  redExperienceDiff             9879 non-null   int64
 35  redCSPerMin                   9879 non-null   float64
 36  redGoldPerMin                 9879 non-null   float64
dtypes: float64(6), int64(31)
memory usage: 2.8 MB

Standardizing the magniture of numberic features using a scaler

In [25]:
# Making a Scaler obj
sc = preprocessing.StandardScaler()
scaled_df = sc.fit_transform(df)
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df.head()

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueFirstBlood,blueKills,blueDeaths,blueAssists,blueDragons,blueHeralds,blueTowersDestroyed,...,redTowersDestroyed,redTotalGold,redAvgLevel,redTotalExperience,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff,redExperienceDiff,redCSPerMin,redGoldPerMin
0,-0.998079,0.316996,-0.379275,0.990429,0.935301,-0.046926,1.071495,-0.753226,-0.481132,-0.210439,...,-0.198353,0.052293,-0.410475,-0.763215,-0.928741,0.367685,-0.256228,-0.013342,-0.928741,0.052293
1,-0.998079,-0.570992,-0.839069,-1.009663,-0.393216,-0.387796,-0.404768,-0.753226,-0.481132,-0.210439,...,4.412301,0.758619,-0.410475,-0.436980,1.033784,0.068504,1.191254,0.593342,1.033784,0.758619
2,-0.998079,-0.404494,-1.298863,-1.009663,0.271042,1.657424,-0.650812,1.327623,-0.481132,-0.210439,...,-0.198353,0.533909,-0.410475,-0.590502,-0.654900,-2.324944,0.483614,0.520436,-0.654900,0.533909
3,-0.998079,1.149484,-0.839069,-1.009663,-0.725346,-0.387796,-0.404768,-0.753226,2.078430,-0.210439,...,-0.198353,-0.007406,0.244627,-0.000609,0.805583,-0.430131,0.544350,-0.013863,0.805583,-0.007406
4,-0.998079,2.925460,0.540312,-1.009663,-0.061087,-0.046926,-0.158724,-0.753226,-0.481132,-0.210439,...,-0.198353,0.613731,0.244627,0.293085,0.349182,1.564408,0.415133,-0.137283,0.349182,0.613731

In [27]:
X = scaled_df.loc[:, scaled_df.columns != 'blueWins']
y = scaled_df[['blueWins']]

In [36]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=123)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(7409, 36) (2470, 36) (7409, 1) (2470, 1)

In [33]:
X_train.mean()

blueWardsPlaced                 0.001416
blueWardsDestroyed             -0.012570
blueFirstBlood                 -0.003273
blueKills                       0.004855
blueDeaths                     -0.010580
blueAssists                     0.008449
blueDragons                    -0.000255
blueHeralds                     0.004939
blueTowersDestroyed             0.004978
blueTotalGold                   0.009462
blueAvgLevel                    0.004569
blueTotalExperience             0.006508
blueTotalMinionsKilled          0.017969
blueTotalJungleMinionsKilled   -0.007120
blueGoldDiff                    0.012699
blueExperienceDiff              0.013656
blueCSPerMin                    0.017969
blueGoldPerMin                  0.009462
redWardsPlaced                  0.011575
redWardsDestroyed              -0.002766
redFirstBlood                   0.003273
redKills                       -0.010580
redDeaths                       0.004855
redAssists                     -0.006834
redDragons                     -0.005385
redHeralds                     -0.005415
redTowersDestroyed              0.002651
redTotalGold                   -0.011152
redAvgLevel                    -0.014001
redTotalExperience             -0.015361
redTotalMinionsKilled          -0.012803
redTotalJungleMinionsKilled    -0.005407
redGoldDiff                    -0.012699
redExperienceDiff              -0.013656
redCSPerMin                    -0.012803
redGoldPerMin                  -0.011152
dtype: float64

In [35]:
X_test.mean()

blueWardsPlaced                -0.004248
blueWardsDestroyed              0.037704
blueFirstBlood                  0.009817
blueKills                      -0.014562
blueDeaths                      0.031736
blueAssists                    -0.025343
blueDragons                     0.000766
blueHeralds                    -0.014815
blueTowersDestroyed            -0.014933
blueTotalGold                  -0.028383
blueAvgLevel                   -0.013705
blueTotalExperience            -0.019523
blueTotalMinionsKilled         -0.053900
blueTotalJungleMinionsKilled    0.021357
blueGoldDiff                   -0.038092
blueExperienceDiff             -0.040963
blueCSPerMin                   -0.053900
blueGoldPerMin                 -0.028383
redWardsPlaced                 -0.034721
redWardsDestroyed               0.008297
redFirstBlood                  -0.009817
redKills                        0.031736
redDeaths                      -0.014562
redAssists                      0.020499
redDragons                      0.016154
redHeralds                      0.016243
redTowersDestroyed             -0.007953
redTotalGold                    0.033452
redAvgLevel                     0.041996
redTotalExperience              0.046078
redTotalMinionsKilled           0.038404
redTotalJungleMinionsKilled     0.016218
redGoldDiff                     0.038092
redExperienceDiff               0.040963
redCSPerMin                     0.038404
redGoldPerMin                   0.033452
dtype: float64